version: "3.8"

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mariadb:latest
    container_name: mariadb-test
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: nextjsdb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
